In [1]:
import numpy as np

In [2]:
threshold = 0.0000000001
max_num_iterations = 1000

In [3]:
def iterative_policy_evaluation(init_state_values, transitions):
    state_values = init_state_values # Index 0 is the terminal state
    for i in range(max_num_iterations):
        for j in range(1, len(state_values)):
            previous_state_values = state_values.copy()
            state_values[j] = -1 + 0.25 * np.sum(state_values[transitions[j]])
        delta = np.linalg.norm(previous_state_values - state_values)
        if delta < threshold:
            break
    print("num iterations:", i + 1)
    return state_values

# Recreating results from the original example

In [4]:
# What state will the agent get to after selecting either {up, down, right, left} from state i
transitions = [
    [0, 0, 0, 0], # The agent is stuck in the terminal state
    [1, 5, 2, 0],
    [2, 6, 3, 1],
    [3, 7, 3, 2],
    [0, 8, 5, 4],
    [1, 9, 6, 4],
    [2, 10, 5, 7],
    [3, 11, 7, 6],
    [4, 12, 9, 8],
    [5, 13, 10, 8],
    [6, 14, 11, 9],
    [7, 0, 11, 10],
    [8, 12, 13, 12],
    [9, 13, 14, 12],
    [10, 14, 0, 13]
]
iterative_policy_evaluation(np.zeros(15), transitions)

num iterations: 265


array([  0., -14., -20., -22., -14., -18., -20., -20., -20., -20., -18.,
       -14., -22., -20., -14.])

# Adding state 15, but not changing any transitions from the other states

In [5]:
new_transitions = [
    [0, 0, 0, 0],
    [1, 5, 2, 0],
    [2, 6, 3, 1],
    [3, 7, 3, 2],
    [0, 8, 5, 4],
    [1, 9, 6, 4],
    [2, 10, 5, 7],
    [3, 11, 7, 6],
    [4, 12, 9, 8],
    [5, 13, 10, 8],
    [6, 14, 11, 9],
    [7, 0, 11, 10],
    [8, 12, 13, 12],
    [9, 13, 14, 12],
    [10, 14, 0, 13],
    [13, 15, 14, 12]
]
iterative_policy_evaluation(np.zeros(16), new_transitions)

num iterations: 270


array([  0., -14., -20., -22., -14., -18., -20., -20., -20., -20., -18.,
       -14., -22., -20., -14., -20.])

# Adding state 15 and changing the transitions for state 13

In [6]:
new_transitions_2 = [
    [0, 0, 0, 0],
    [1, 5, 2, 0],
    [2, 6, 3, 1],
    [3, 7, 3, 2],
    [0, 8, 5, 4],
    [1, 9, 6, 4],
    [2, 10, 5, 7],
    [3, 11, 7, 6],
    [4, 12, 9, 8],
    [5, 13, 10, 8],
    [6, 14, 11, 9],
    [7, 0, 11, 10],
    [8, 12, 13, 12],
    [9, 15, 14, 12],
    [10, 14, 0, 13],
    [13, 15, 14, 12]
]
iterative_policy_evaluation(np.zeros(16), new_transitions_2)

num iterations: 268


array([  0., -14., -20., -22., -14., -18., -20., -20., -20., -20., -18.,
       -14., -22., -20., -14., -20.])