In [1]:
import numpy as np
np.random.seed(7)
import random
random.seed(7)
import matplotlib.pyplot as plt
from trajectory_sampling import *

In [3]:
NUM_STATES = 4
NUM_ACTIONS = 2
b = 3
env = Environment(NUM_STATES, NUM_ACTIONS, b)
env.transitions

[[(array([2, 3, 2]),
   array([ 1.50747188,  1.18367808, -0.59433183, -1.51004067])),
  (array([0, 1, 3]), array([0.21465687, 1.84624536, 0.16640132, 0.07166549]))],
 [(array([1, 0, 3]),
   array([ 0.42034714, -0.9760654 ,  1.06985315,  0.1666724 ])),
  (array([2, 3, 3]),
   array([-0.09477545,  1.19308592, -0.36881847, -1.90636988]))],
 [(array([2, 1, 2]),
   array([ 1.65642429, -0.88618447, -2.51466001,  0.04704161])),
  (array([0, 0, 1]),
   array([-1.32211549, -2.16867984,  0.67608609,  0.62706529]))],
 [(array([0, 2, 0]),
   array([-0.00998003,  1.43402678,  0.29110214, -0.23440229])),
  (array([2, 1, 1]),
   array([-0.19285546, -1.77801285,  0.6547057 ,  0.8943523 ]))]]