In [1]:
import numpy as np
np.random.seed(7)
import random
random.seed(7)
import matplotlib.pyplot as plt
from trajectory_sampling import *

In [2]:
NUM_STATES = 3
NUM_ACTIONS = 2
b = 2
EPS = 0.1
env = Environment(NUM_STATES, NUM_ACTIONS, b)
env.transitions

[[(array([2, 1]), array([-0.38546851, -0.43497813, -0.38546851])),
  (array([1, 0]), array([-0.22025144,  0.02006439, -0.34983013]))],
 [(array([2, 1]), array([ 1.18707736, -1.61686249,  1.18707736])),
  (array([1, 2]), array([ 1.20094576, -0.20413855, -0.20413855]))],
 [(array([2, 0]), array([0.27445992, 0.12388091, 0.27445992])),
  (array([1, 2]), array([-1.52652453, -1.10711737, -1.10711737]))]]

In [3]:
Q = np.array([
    [0.0, 2],
    [2, 0],
    [0, 0]
])
count = [0, 0]
for i in range(1000):
    a = eps_greedy_action_selection(Q, 1, 0.1)
    count[a] += 1
print(count)

[958, 42]


In [4]:
update_Q(Q, env.transitions, 0, 0)
Q

array([[0.49225216, 2.        ],
       [2.        , 0.        ],
       [0.        , 0.        ]])