In [1]:
import numpy as np
np.random.seed(7)
import random
random.seed(7)
import matplotlib.pyplot as plt
from trajectory_sampling import *

In [2]:
NUM_STATES = 5
NUM_ACTIONS = 2
b = 3
EPS = 0.1
env = Environment(NUM_STATES, NUM_ACTIONS, b)
env.transitions

[[(array([0, 3, 2]),
   array([-0.03710022,  0.39946285, -1.09344174, -0.88903401])),
  (array([4, 0, 3]),
   array([ 0.83083986, -0.34983013, -0.38108715,  0.83083986]))],
 [(array([1, 4, 2]),
   array([-0.01496821, -0.08313583,  0.74878108, -0.08313583])),
  (array([2, 4, 1]),
   array([-0.28028551, -0.95166343, -2.14511962, -0.95166343]))],
 [(array([2, 4, 1]),
   array([-0.04104215,  0.13095382,  0.5197088 ,  0.13095382])),
  (array([4, 3, 0]),
   array([-0.21297954,  0.46797054,  0.41266062, -0.21297954]))],
 [(array([0, 4, 2]),
   array([-0.50541495, -1.0443414 ,  1.90816149, -1.0443414 ])),
  (array([0, 1, 2]), array([0.21465687, 1.84624536, 0.16640132, 0.07166549]))],
 [(array([1, 2, 0]),
   array([ 1.06985315,  0.1666724 , -0.16569661, -1.1334848 ])),
  (array([4, 0, 1]),
   array([-0.88618447,  0.03993667,  1.65642429, -0.88618447]))]]

In [3]:
counts = [0, 0, 0]
for i in range(1000000):
    expected_reward, next_state, reached_terminal_state = env.take_action(0, 1)
    if next_state == 4:
        counts[0] += 1
    if next_state == 0:
        counts[1] += 1
    if next_state == 3:
        counts[2] += 1
print(counts)

[400038, 300036, 299926]
